### ISSUE TITLE
Misfunction on crontab

### ISSUE THREAD

**Issue by acamacho85** [sassoftware/SAS-lsm#3]
Hi team,

I really love this tool, so hope you can help me with the error I have.
I use this tool for many of my task, including activating/deactivating crontab jobs on the start/stop of the SAS services, backups and archival processes. 
Recently there is the need to keep a constant monitoring on the SAS services across the SAS Server. To solve this I added a crontab job to check the status of the SAS services using LSM utility. For this I created a copy of my config file and added the following line to the crontab:
*/5 * * * * bash /apps/thirdparty/lsm/SAS_lsm -s -c /apps/thirdparty/lsm/sas_ci_cron.cfg  >/dev/null 2>&1

At the beginning this was working like a charm, however and apparently without any reason I started receiving emails regarding the failure on the status check using the tool, so when the team took a look into the services all was working properly, also if we executed the "status" functionality manually it was working properly, so the decision was to remove the crontab job until we figure out what happened and to make sure we can avoid false positives cases as this one.

The false positive alarms were running from Tue Jul 12 23:00:13 EDT 2022 and until Wed Jul 13 00:30:12 EDT 2022 , at that time there were no additional reports, there was no any outage, all servers were accessible, but the tool triggered by crontab was not working properly, also manual executions returned the correct status.
![Screenshot_SAS-LSM_status](https://user-images.githubusercontent.com/63619877/181823391-007a524a-85ff-479f-8888-31e169d9e309.png)

**Comment by Greg-Arledge** [comment]
Hi acamacho 85,

In this case the error is not a false positive.  The error message indicates that the SASlsm utility does not understand the output from the sas.servers status command on 3 of the tiers.  Essentially it is not claiming that anything is down, just that it can't determine if it is up or down.

Can you share/paste the config file that the cronjob was using?  And the one you use for manual checks.

**Comment by acamacho85** [comment]
Hi Greg,
Just to clarify, is not failing every time, it was set and was working properly but some hours after that, it began failing.
What I want to avoid is that this behavior happen especially in my non-working hours alerting users with these alarms when services are available.

This is the config file we use for manual validations:
cat sas_ci.cfg
##########################################################################################################################################
## BEGIN MISCELLANEOUS VARIABLES

## REQUIRED: CONFIGURATION DIRECTORY (E.G. /opt/SAS/94/production/config/Lev1)
## if you have unique CONFIGURATION directories for the TIERs in your deployment, you can define the CONFIGDIR value before each TIER definition
CONFIGDIR=/apps/config/Lev1

## REQUIRED: if you have unique INSTANCE OWNER userids for the TIERS in your deployment, you can define the INSTID value before each TIER definition
INSTID=svc_npebidsasadm

## REQUIRED: NUMBER OF TIERS IN THIS CONFIGURATION FILE
MAXTIERS=4

# REQUIRED/CONFIGURABLE: SSH OPTIONS
SSHOPTIONS="-q -o StrictHostKeyChecking=no -o PasswordAuthentication=no"

## REQUIRED/CONFIGURABLE NUMBER OF RETRIES
MAXRETRY=10

## REQUIRED/CONFIGURABLE: SLEEP INTERVAL IN SECONDS PER RETRY
SLEEP=6

## REQUIRED/CONFIGURABLE: STATUS REPORT ROOT DIRECTORY
STATUSROOT=/apps/thirdparty/lsm/logs

## REQUIRED/CONFIGURABLE: offset in hours that is used to trim centralized log files
TRIMOFFSET=1

## OPTIONAL: SAS ADMINISTRATOR EMAIL ADDRESS(ES)
## REMOVE # in COLUMN 1 OF THE VARIABLE TO ACTIVATE
#SASADMIN="ADDRESS1 ADDRESS2 ADDRESSN"
SASADMIN="dps.deap.sasplatform@dell.com"

## END MISCELLANEOUS VARIABLES

##########################################################################################################################################


##########################################################################################################################################
## BEGIN OPTIONAL sas.servers services Tier Descriptor Template
## REMOVE # in COLUMN 1 OF TIER VARIABLES AND REPLACE ARRAY ELEMENT VALUE "N" WITH SEQUENTIAL NUMERIC VALUE TO ACTIVATE

TIERNAME[1]='Metadata'
TIERINST[1]=${INSTID}
TIERHOST[1]=sasnldurdev01
TIERSTAR[1]="${CONFIGDIR}/sas.servers start"
TIERSTOP[1]="${CONFIGDIR}/sas.servers stop"
TIERREST[1]="${CONFIGDIR}/sas.servers restart"
TIERSTAT[1]="${CONFIGDIR}/sas.servers status"
TIERSTAS[1]='is NOT up'
TIERSTOS[1]='is UP'
TIERLOGD[1]=${CONFIGDIR}
TIERTYPE[1]='standard'
TIEREXIT[1]=/apps/thirdparty/lsm/user_scripts

TIERNAME[2]='MA Compute'
TIERINST[2]=${INSTID}
TIERHOST[2]=sasnldurdev02
TIERSTAR[2]="${CONFIGDIR}/sas.servers start"
TIERSTOP[2]="${CONFIGDIR}/sas.servers stop"
TIERREST[2]="${CONFIGDIR}/sas.servers restart"
TIERSTAT[2]="${CONFIGDIR}/sas.servers status"
TIERSTAS[2]='is NOT up'
TIERSTOS[2]='is UP'
TIERLOGD[2]=${CONFIGDIR}
TIERTYPE[2]='standard'
TIEREXIT[2]=/apps/thirdparty/lsm/user_scripts

TIERNAME[3]='MO Compute'
TIERINST[3]=${INSTID}
TIERHOST[3]=sasnldurdev03
TIERSTAR[3]="${CONFIGDIR}/sas.servers start"
TIERSTOP[3]="${CONFIGDIR}/sas.servers stop"
TIERREST[3]="${CONFIGDIR}/sas.servers restart"
TIERSTAT[3]="${CONFIGDIR}/sas.servers status"
TIERSTAS[3]='is NOT up'
TIERSTOS[3]='is UP'
TIERLOGD[3]=${CONFIGDIR}
TIERTYPE[3]='standard'
TIEREXIT[3]=/apps/thirdparty/lsm/user_scripts

TIERNAME[4]='Midtier'
TIERINST[4]=${INSTID}
TIERHOST[4]=sasnldurdev04
TIERSTAR[4]="${CONFIGDIR}/sas.servers start"
TIERSTOP[4]="${CONFIGDIR}/sas.servers stop"
TIERREST[4]="${CONFIGDIR}/sas.servers restart"
TIERSTAT[4]="${CONFIGDIR}/sas.servers status"
TIERSTAS[4]='is NOT up'
TIERSTOS[4]='is UP'
TIERLOGD[4]=${CONFIGDIR}
TIERTYPE[4]='standard'
TIEREXIT[4]=/apps/thirdparty/lsm/user_scripts

## END OPTIONAL sas.servers services Tier Descriptor Template
##########################################################################################################################################


This is the one for the crontab, as you can see there is no difference between files, just created 2 separated files as per the recommendations to avoid any conflict while running the same command multiple times on the servers.

cat sas_ci_cron.cfg
##########################################################################################################################################
## BEGIN MISCELLANEOUS VARIABLES

## REQUIRED: CONFIGURATION DIRECTORY (E.G. /opt/SAS/94/production/config/Lev1)
## if you have unique CONFIGURATION directories for the TIERs in your deployment, you can define the CONFIGDIR value before each TIER definition
CONFIGDIR=/apps/config/Lev1

## REQUIRED: if you have unique INSTANCE OWNER userids for the TIERS in your deployment, you can define the INSTID value before each TIER definition
INSTID=svc_npebidsasadm

## REQUIRED: NUMBER OF TIERS IN THIS CONFIGURATION FILE
MAXTIERS=4

# REQUIRED/CONFIGURABLE: SSH OPTIONS
SSHOPTIONS="-q -o StrictHostKeyChecking=no -o PasswordAuthentication=no"

## REQUIRED/CONFIGURABLE NUMBER OF RETRIES
MAXRETRY=10

## REQUIRED/CONFIGURABLE: SLEEP INTERVAL IN SECONDS PER RETRY
SLEEP=6

## REQUIRED/CONFIGURABLE: STATUS REPORT ROOT DIRECTORY
STATUSROOT=/apps/thirdparty/lsm/logs

## REQUIRED/CONFIGURABLE: offset in hours that is used to trim centralized log files
TRIMOFFSET=1

## OPTIONAL: SAS ADMINISTRATOR EMAIL ADDRESS(ES)
## REMOVE # in COLUMN 1 OF THE VARIABLE TO ACTIVATE
#SASADMIN="ADDRESS1 ADDRESS2 ADDRESSN"
SASADMIN="dps.deap.sasplatform@dell.com"

## END MISCELLANEOUS VARIABLES

##########################################################################################################################################


##########################################################################################################################################
## BEGIN OPTIONAL sas.servers services Tier Descriptor Template
## REMOVE # in COLUMN 1 OF TIER VARIABLES AND REPLACE ARRAY ELEMENT VALUE "N" WITH SEQUENTIAL NUMERIC VALUE TO ACTIVATE

TIERNAME[1]='Metadata'
TIERINST[1]=${INSTID}
TIERHOST[1]=sasnldurdev01
TIERSTAR[1]="${CONFIGDIR}/sas.servers start"
TIERSTOP[1]="${CONFIGDIR}/sas.servers stop"
TIERREST[1]="${CONFIGDIR}/sas.servers restart"
TIERSTAT[1]="${CONFIGDIR}/sas.servers status"
TIERSTAS[1]='is NOT up'
TIERSTOS[1]='is UP'
TIERLOGD[1]=${CONFIGDIR}
TIERTYPE[1]='standard'
TIEREXIT[1]=/apps/thirdparty/lsm/user_scripts

TIERNAME[2]='MA Compute'
TIERINST[2]=${INSTID}
TIERHOST[2]=sasnldurdev02
TIERSTAR[2]="${CONFIGDIR}/sas.servers start"
TIERSTOP[2]="${CONFIGDIR}/sas.servers stop"
TIERREST[2]="${CONFIGDIR}/sas.servers restart"
TIERSTAT[2]="${CONFIGDIR}/sas.servers status"
TIERSTAS[2]='is NOT up'
TIERSTOS[2]='is UP'
TIERLOGD[2]=${CONFIGDIR}
TIERTYPE[2]='standard'
TIEREXIT[2]=/apps/thirdparty/lsm/user_scripts

TIERNAME[3]='MO Compute'
TIERINST[3]=${INSTID}
TIERHOST[3]=sasnldurdev03
TIERSTAR[3]="${CONFIGDIR}/sas.servers start"
TIERSTOP[3]="${CONFIGDIR}/sas.servers stop"
TIERREST[3]="${CONFIGDIR}/sas.servers restart"
TIERSTAT[3]="${CONFIGDIR}/sas.servers status"
TIERSTAS[3]='is NOT up'
TIERSTOS[3]='is UP'
TIERLOGD[3]=${CONFIGDIR}
TIERTYPE[3]='standard'
TIEREXIT[3]=/apps/thirdparty/lsm/user_scripts

TIERNAME[4]='Midtier'
TIERINST[4]=${INSTID}
TIERHOST[4]=sasnldurdev04
TIERSTAR[4]="${CONFIGDIR}/sas.servers start"
TIERSTOP[4]="${CONFIGDIR}/sas.servers stop"
TIERREST[4]="${CONFIGDIR}/sas.servers restart"
TIERSTAT[4]="${CONFIGDIR}/sas.servers status"
TIERSTAS[4]='is NOT up'
TIERSTOS[4]='is UP'
TIERLOGD[4]=${CONFIGDIR}
TIERTYPE[4]='standard'
TIEREXIT[4]=/apps/thirdparty/lsm/user_scripts

## END OPTIONAL sas.servers services Tier Descriptor Template
##########################################################################################################################################

**Comment by Greg-Arledge** [comment]
In your config file for the crontab status runs, try adding "-o ConnectTimeout=30" in the SSHOPTIONS variable so that it looks like this:

SSHOPTIONS="-q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30"

Let me know if the behavior is any different.

**Comment by acamacho85** [comment]
Hi Greg,

I've updated the config files but I got the same behavior after one day.

COMMAND: SAS_lsm -s -c /apps/thirdparty/lsm/sas_ci_cron.cfg

<< INFO >> Checking SAS_lsm version...
<< INFO >> Current SAS_lsm version 4.1.0 was successfully verified as up-to-date.

Configuration file validation [/apps/thirdparty/lsm/sas_ci_cron.cfg] status [begin] Configuration file validation [/apps/thirdparty/lsm/sas_ci_cron.cfg] status [end success]

Tue Aug  2 21:15:02 EDT 2022: action [services_status] tier [1:Metadata] host [sasnldurdev01] status [begin]
  << EXECUTING >> /apps/config/Lev1/sas.servers status
  <<TIER STATUS>> ALL tier services are operational
                  SAS Metadata Server 1 is UP
                  SAS Environment Manager Agent is UP Tue Aug  2 21:15:02 EDT 2022: action [services_status] tier [1:Metadata] host [sasnldurdev01] status [end success]

Tue Aug  2 21:15:02 EDT 2022: action [services_status] tier [2:MA Compute] host [sasnldurdev02] status [begin]
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status
  <<TIER STATUS>> unable to determine tier status Tue Aug  2 21:15:05 EDT 2022: action [services_status] tier [2:MA Compute] host [sasnldurdev02] status [end failed - 007]

Tue Aug  2 21:15:05 EDT 2022: action [services_status] tier [3:MO Compute] host [sasnldurdev03] status [begin]
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev03 /apps/config/Lev1/sas.servers status
  <<TIER STATUS>> unable to determine tier status Tue Aug  2 21:15:08 EDT 2022: action [services_status] tier [3:MO Compute] host [sasnldurdev03] status [end failed - 007]

Tue Aug  2 21:15:08 EDT 2022: action [services_status] tier [4:Midtier] host [sasnldurdev04] status [begin]
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  << EXECUTING >> ssh -q -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev04 /apps/config/Lev1/sas.servers status
  <<TIER STATUS>> unable to determine tier status Tue Aug  2 21:15:11 EDT 2022: action [services_status] tier [4:Midtier] host [sasnldurdev04] status [end failed - 007]

Please see /apps/thirdparty/lsm/logs/sas_ci_cron.cfg/report.status for execution details


<<FAILURE>> Deployment tier services are in an unknown state

**Comment by ajforeman** [comment]
When this happened and you manually checked service status to verify, did you do that via SAS-lsm or did you log in to the individual machines and directly run `sas.servers status`?

The behavior seems to me like ssh either fails or takes too long to return (even after the 30 second timeout was added), but it would be odd if that happened in cron but not in a manual execution of the SAS-lsm script. Both of those should be doing the exact same thing and making the same ssh call. Even more odd is that it sounds like it is inconsistent, which would make me think a network or sshd-related issue.

If you're able to catch it when it happens, try to manually run the ssh command it shows after _<< EXECUTING >>_ and see what it returns. Swap the **-q** (quiet) for **-vvv** for maximum verbosity (example:  `ssh -vvv -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30 svc_npebidsasadm@sasnldurdev02 /apps/config/Lev1/sas.servers status` ).

Alternatively, update your SAS-lsm configuration file and replace the **-q** with **-vvv** in SSHOPTIONS (example: `SSHOPTIONS="-vvv -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=30"` ). This will make SAS-lsm's output look like a mess, but it doesn't seem to prevent SAS-lsm from understanding any of the command responses that it's reading, at least for status... just tested on my sandbox and it was still able to determine deployment state.

If we can see ssh returning some error message when the behavior occurs, that might explain what's going on.

**Comment by acamacho85** [comment]
Hi Andy,
Usually when we receive the notification we check in both ways, this is with the LSM (using a different .cfg file) and with the sas.servers scripts. Also we have tested using the cfg file used for the crontab job and we get good response (weird). Anyway I'm adding the verbose (-vvv) options and will let you know what happen next time.

**Comment by acamacho85** [comment]
Hi Andy / Greg,

Using the verbose I was able to identify the root cause of the issue. This was caused due to our accounts are authenticated by GSSAPIAuthentication. When GSSAPIAuthentication is enabled , SSH uses Kerberos ticket to authenticate the user.
If a cron job expects access to something in your home directory, (like /.ssh/authorized_keys) you need to make sure you have a valid kerberos ticket for the cronjob to be able to access.

In my case the ticket expired after 10 hours hence cron tab jobs start failing. To solve the issue along with the execution of the LSM tool I submit the kinit command to create a new or renew ticket-granting every 8 hours.
